version: '2'
services:
  agora:
    image: 'sagebionetworks/agora-app'
    environment:
      - MONGO_URI=mongodb://mongodb/agora
    restart: always
    expose:
      - '5000'
    networks:
      - front-tier
  # NGINX will reverse proxy the express application
  nginx:
    image: 'sagebionetworks/agora-nginx'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - front-tier
    volumes:
      - ./config/snippets:/snippets

networks:
  front-tier:
    external:
      name: agora_network
